/**
 * POST /api/create-payment — charges a card token from the Web Payments
 * SDK (js/checkout.js) via Square's Payments API.
 *
 * The request body only ever sends an `itemKey` (e.g. "gift-50",
 * "plan-drop-in-class") — never a raw amount. The authoritative price for
 * that key is looked up here, server-side, from data/checkout-items.json
 * (generated by generator/pages.py from the same prices shown on the
 * page). A tampered request that claims a different amount is ignored;
 * whatever the real price for that key is gets charged, full stop.
 */
var crypto = require("crypto");
var checkoutItems = require("../data/checkout-items.json");
var square = require("../lib/square");

function isValidEmail(email) {
  return typeof email === "string" && /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

module.exports = async function handler(req, res) {
  if (req.method !== "POST") {
    res.setHeader("Allow", "POST");
    return res.status(405).json({ error: "Method not allowed" });
  }

  var accessToken = process.env.SQUARE_ACCESS_TOKEN;
  var locationId = process.env.SQUARE_LOCATION_ID;
  if (!accessToken || !locationId) {
    return res.status(500).json({
      error: "Payments aren't configured on this server yet — set SQUARE_ACCESS_TOKEN and SQUARE_LOCATION_ID (see README).",
    });
  }

  // Vercel's Node runtime parses a JSON request body into req.body
  // automatically. On a different host (e.g. a standalone Express server)
  // you'd need body-parsing middleware (express.json()) in front of this.
  var body = req.body || {};
  var itemKey = body.itemKey;
  var sourceId = body.sourceId;
  var buyerEmail = body.buyerEmail;

  var item = checkoutItems[itemKey];
  if (!item) {
    return res.status(400).json({ error: "Unknown item." });
  }
  if (!sourceId || typeof sourceId !== "string") {
    return res.status(400).json({ error: "Missing payment token." });
  }
  if (buyerEmail && !isValidEmail(buyerEmail)) {
    return res.status(400).json({ error: "That email address doesn't look right." });
  }

  try {
    var result = await square.squareRequest("/v2/payments", {
      method: "POST",
      body: {
        idempotency_key: crypto.randomUUID(),
        source_id: sourceId,
        location_id: locationId,
        amount_money: { amount: item.amountCents, currency: "USD" },
        note: item.label,
        buyer_email_address: buyerEmail || undefined,
      },
    });

    return res.status(200).json({
      success: true,
      paymentId: result.payment && result.payment.id,
      receiptUrl: result.payment && result.payment.receipt_url,
    });
  } catch (err) {
    // Full detail (card decline reason, etc.) is logged server-side only —
    // the client gets a generic, non-leaky message either way.
    console.error("Square create-payment error:", err.squareErrors || err.message);
    var clientError =
      err.status && err.status < 500
        ? "We couldn't process that card. Double-check the details and try again, or use a different card."
        : "Something went wrong on our end processing that payment. Please try again in a moment.";
    return res.status(err.status && err.status < 500 ? 402 : 500).json({ error: clientError });
  }
};
